[server]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="
outer_port = 8002
outer_addr = "127.0.0.1:8002"
inner_port = 5002
private_key = "Xn5D7GlIQBcgizfYhv0cDhQx1H7sY/f0/3k9IOT56ak="
epoch_interval = 10000

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="

[[peers]]
connection_string = "127.0.0.1:8002"
id = "srv_2"
length = 3
bls_pub_key = "iQ8xF+NzeZESxJQwPwXTF0RjIYajsalQhG3Tw9+57+zQETWwli5pWrAJZWUuiKIv"
dalek_pub_key = "DLwkF748vwkOVURRtC93KVxcY9anoNssI9+9DwL+mEk="
