[server]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="
outer_port = 8006
outer_addr = "127.0.0.1:8006"
inner_port = 6006
private_key = "kDkow02x4Ho20pyLmOtEypcvHy3h/f6vKCLxO7J68zk="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="

[[peers]]
connection_string = "127.0.0.1:8006"
id = "srv_6"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "hlNE+AqS554Yack7mXYuWnLeCxS29zuuDTAMKChCLpN2CXmZXwDYDESTA6CVwWcK"
dalek_pub_key = "drUvHoM3HTjix9sqwg7mD+JIW2N0TwdBafJ2Ri+Xgk4="
