[server]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="
outer_port = 8008
outer_addr = "127.0.0.1:8008"
inner_port = 5008
private_key = "+atbpMwd07+DgDbCzCtv8NC+djmREjs4tZFgaH+jG2I="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "sFKwMGzFEpkClC/9EHEQ9KEPeP0Un0ia0X6WqfVvwiWnZEhQjfqf8j7vtlZWYxkc"
dalek_pub_key = "QK1DtZh/RQK1gv0FDqPUaxiQqNrEMvE/uh6ypVjo4pI="
