[server]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="
outer_port = 8012
outer_addr = "127.0.0.1:8012"
inner_port = 5012
private_key = "mp2FPG5VJH54+86tJoSaeLQ6jwORofcuU96jeI1yksE="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "ubRqswfGZJs5y05xRQxrr/XVCtBAOKonVSx+S2EBLHlwuuHWjs7WHZM9Of+v+xms"
dalek_pub_key = "hOmm6c9KGAAOP0J5DIx741/lguPkM1Aedlbver8pl8c="
