[server]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="
outer_port = 8013
outer_addr = "127.0.0.1:8013"
inner_port = 6013
private_key = "l6p3to9lKMxijRuzoc8O2nNbrjif3Xp5fHkkY9YIYyw="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="

[[peers]]
connection_string = "127.0.0.1:8013"
id = "srv_13"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "rQR3R7b2zdJH2o+NbyhnhU6Lvfm0XMLr3YjSX6eEMv6kruuItAPamLLW/KVaYx0i"
dalek_pub_key = "CdQ8c/HvYDLbgFldBV+tf87mcwsFmHEDI1istobLf/A="
