[server]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="
outer_port = 8012
outer_addr = "127.0.0.1:8012"
inner_port = 6012
private_key = "GywM+Ohdw/HPVjrwcKaD7HjS3FtjcxCBzEB8bHFmBds="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="

[[peers]]
connection_string = "127.0.0.1:8012"
id = "srv_12"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "pIyqIkT7KTt6ba3IgkUFKMPmi6BQmdz/ikWGT4wiBaey0zeI2POZCj52oRkK3dGN"
dalek_pub_key = "C/QZJONkGY6H4Uy8cmq2Nl3XhkjgaSeGJsoaiiVjx6o="
