[server]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="
outer_port = 8005
outer_addr = "127.0.0.1:8005"
inner_port = 6005
private_key = "zSihOcTdjRj57XwSq8ZqV6qsIPO0fLQ/PvCXBaF9p8Q="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="

[[peers]]
connection_string = "127.0.0.1:8005"
id = "srv_5"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "l49gyCqu+GA3OaM9M1IadrK8HeQklFCwDIxaVoTTMSxZn1d2f0Asao2XWzJdcGck"
dalek_pub_key = "l+fS1CPxNriNE6T+f2u/2ig3Y2HJo5AW6OOy1echINo="
