[server]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="
outer_port = 8010
outer_addr = "127.0.0.1:8010"
inner_port = 6010
private_key = "Knv95BXDQ9JCeL5EmvMtQH6LHd8tF1Y6O4GnOctvgYY="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="

[[peers]]
connection_string = "127.0.0.1:8010"
id = "srv_10"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "teORFBeSGfi2PKb3MfVZVEvwOjBI17MlQVQLcvFBdoesoeeheJKiNZkWc6noChA2"
dalek_pub_key = "T4T0mvGgk9e7jrVZAESF/JvQ9t9yIB4jn3eKNU1+u7o="
