[server]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="
outer_port = 8007
outer_addr = "127.0.0.1:8007"
inner_port = 6007
private_key = "pzftT0v4QsgF7++WFLuz3k7Y0sIp0VHj1EqW1YDsJp0="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="

[[peers]]
connection_string = "127.0.0.1:8007"
id = "srv_7"
prefix = "BA=="
prefix_length = 3
length = 7
bls_pub_key = "uWakRUJX1Fi6pG9zVSZXJdIqpmx/q9fYZ3iFdv648mWIl/nMGRauVGiroBEzNsts"
dalek_pub_key = "cwdhF0BA3PsxdUmA/BNQ9bKFoC4j2o7t23loCwXiblA="
