[server]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="
outer_port = 8009
outer_addr = "127.0.0.1:8009"
inner_port = 6009
private_key = "gH67FSWqYNxcoDXIphEcHloiDBgNre/pnKGaunSNigM="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="

[[peers]]
connection_string = "127.0.0.1:8009"
id = "srv_9"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "pMGkY3icfp6tfIm5w/wVUN9JD87CUy6AOLeOR2BXT+pq03BCcpaChjNUbcYfx6ev"
dalek_pub_key = "zObMHa4tgt/r0BaNHqy0CUhwTTlh+F8Kwrszrrot5wc="
