[server]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="
outer_port = 8011
outer_addr = "127.0.0.1:8011"
inner_port = 6011
private_key = "T0wB17hr2JsC+apgU47K2r+vG3Nu9f04tz3Ng0zCMq4="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="

[[peers]]
connection_string = "127.0.0.1:8011"
id = "srv_11"
prefix = "AQ=="
prefix_length = 3
length = 7
bls_pub_key = "o+3Wa76HuOASzsy9U/Y5nsSXAFTDsj9rucmdGtz1OTyrA+I/Mi7zgyh+YgK5Doey"
dalek_pub_key = "YNgLjWG3S9P/qO9uPBGZiAFlQ7509AFtIM9NaPYufnw="
