[server]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="
outer_port = 8008
outer_addr = "127.0.0.1:8008"
inner_port = 6008
private_key = "W7vafvUg3uByIdms2vAJQ8b5xPqeylmPHopUkV8hUjw="
epoch_interval = 1000

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="

[[peers]]
connection_string = "127.0.0.1:8008"
id = "srv_8"
prefix = "Ag=="
prefix_length = 3
length = 7
bls_pub_key = "lGwP8usvKqPGyFHn4Y1JbaFbN6UcaKZJqaxEj5PhYLgg8VTBsuVyd2kkHr7kUV1q"
dalek_pub_key = "PjoBzfm5kMG/kmYlDuItAR4G/fwMIbYcAE1HN6UTJrA="
